config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: :login }, skip: [:registrations]
  as :user do
    get 'me/edit' => 'registrations#edit', :as => 'edit_user_registration'
    put 'user' => 'registrations#update', :as => 'user_registration'
  end

  root 'home#index'
  resources :calls, only: [:show, :index]
  resources :warranties, only: [:show, :index]

  namespace :admin do
    resources :users, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :warranties, except: [:show, :index] do
      get :fields_autocomplete, on: :collection
    end
    resources :calls, except: [:show, :index] do
      member do
        put :call_expect
        put :call_in_progress
      end
    end
    resources :boilers, except: [:show, :index] do
      resources :product_models, only: [:create, :update, :destroy], shallow: true
    end
    resources :masters, except: [:show, :index, :edit]
    resources :users, only: [:index, :show, :update, :destroy]

    get '/serial_autocomplete', to: 'calls#serial_autocomplete'
  end
end

app/models/call.rb
class Call < ApplicationRecord
  include PgSearch
  include Filterable
  include Scopes::Call

  pg_search_scope :search_by, against: [:id, :username, :phone, :adress, :status, :guarantee, :error], using: { tsearch: { prefix: true } },
                              associated_against: { product_model: :name, master: :name, warranty: :serial }

  validates :username, :adress, :call_date, :phone, :error, presence: true
  validates :guarantee, inclusion: { in: [true, false] }
  validates :status, inclusion: { in: %w[success canceled in_progress expect] }
  validates :serial_code, presence: true, if: -> { guarantee? }

  before_save :clear_warranty

  belongs_to :warranty, optional: true
  belongs_to :product_model
  belongs_to :master, optional: true
  belongs_to :user

  def serial_code
    warranty.try(:serial)
  end

  def serial_code=(serial)
    self.warranty = Warranty.find_by(serial: serial) if serial.present?
  end

  def self.pg_search(query)
    query.blank? ? [] : search_by(query)
  end

  def clear_warranty
    self.warranty = nil unless guarantee?
  end
end

app/models/scopes/call.rb
module Scopes
  module Call
    extend ActiveSupport::Concern

    included do
      scope :by_id, lambda { |id|
        where(id: id)
      }

      scope :by_call_date, lambda { |call_date|
        where('call_date > ?', call_date)
      }

      scope :by_username, lambda { |username|
        where('username ILIKE ?', "%#{username}%")
      }

      scope :by_phone, lambda { |phone|
        where('phone ILIKE ?', "%#{phone}%")
      }

      scope :by_adress, lambda { |adress|
        where('adress ILIKE ?', "%#{adress}%")
      }

      scope :by_product_model_name, lambda { |product_model_name|
        references(:product_model).where('product_models.name ILIKE ?', "%#{product_model_name}%")
      }

      scope :by_error, lambda { |error|
        where('error ILIKE ?', "%#{error}%")
      }

      scope :by_master_name, lambda { |master_name|
        references(:master).where('masters.name ILIKE ?', "%#{master_name}%")
      }

      scope :by_created_at, lambda { |created_at|
        where('created_at > ?', created_at)
      }

      scope :by_status, lambda { |status|
        where('status ILIKE ?', "%#{status}%")
      }

      scope :by_guarantee, lambda { |guarantee|
        where(guarantee: guarantee)
      }
    end
  end
end

app/controllers/admin/calls_controller.rb
class Admin::CallsController < Admin::AdminController
  include ApplicationHelper
  helper_method :sort_column, :sort_direction
  before_action :find_id, only: [:update, :edit, :destroy, :call_expect, :call_in_progress]
  before_action :boilers_all, only: [:new, :create]

  def new
    @call = current_user.calls.build
  end

  def create
    @call = current_user.calls.build(call_params)

    if @call.save
      redirect_to calls_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @call.update(call_params)
      redirect_to call_path
    else
      render :edit
    end
  end

  def destroy
    @call.destroy
    redirect_to calls_path
  end

  def serial_autocomplete
    respond_to do |format|
      format.json do
        render json: Warranty.serials(params[:term])
      end
    end
  end

  def call_expect
    @call.update(status: 'expect')
    redirect_to @call
  end

  def call_in_progress
    @call.update(status: 'in_progress')
    redirect_to @call
  end

  private

  def call_params
    params.require(:call).permit(:product_model_id, :username, :phone, :adress, :call_date, :status, :master_id, :error,
                                 :guarantee, :serial_code, :whycanceled, :infosuccess, :comment)
  end

  def find_id
    @call = Call.find(params[:id])
  end

  def boilers_all
    @boilers = Boiler.all
  end
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.json do
        scope = Call.all
        render json: ApplicationDatatable.new(view_context, scope.includes(:product_model, :master))
      end
    end
  end

  def show
    @call = Call.find(params[:id])
  end
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/views/calls/index.html.slim
section
  .row.mt5
    article.col-xs-12
      .jarviswidget.jarviswidget-color-blueDark
        header
          h2 Вызовы
        div
          .widget-body.no-padding
            table#calls.table.table-bordered.table-striped.mb0 cellspacing="0" width='100%' data-source="#{calls_path(format: :json)}"
              thead
                tr
                  - CallPresenter.columns.each do |column|
                    = k(:datatable_column, column).filter_cell
                tr
                  - CallPresenter.columns.each do |column|
                    = k(:datatable_column, column).cell

app/views/calls/show.html.slim
#wid-id-0.jarviswidget.jarviswidget-color-blueDark.jarviswidget-sortable
  header.ui-sortable-handle
    span.widget-icon
      i.fa.fa-phone
    h2
      | Вызов #
      = @call.id
    .jarviswidget-ctrls
      = link_to edit_admin_call_path(@call), class: 'button-icon' do
        i.fa.fa-cog
      = link_to admin_call_path(@call), class: 'button-icon', method: :delete, data: { confirm: "Вы уверены что хотите удалить вызов #{@call.username}?"} do
        i.fa.fa-trash
  div
    .widget-body
      table#user.table.table-bordered.table-striped[style="clear: both"]
        tbody
          tr
            td style="width:15%;" Имя
            td = @call.username
          tr
            td Котел
            td = @call.product_model.full_name
          tr
            td Телефон
            td = @call.phone
          tr
            td Адрес
            td
              span.ymaps-geolink = @call.adress
          tr
            td Неисправность
            td = @call.error
          tr
            td Дата звонка клиента
            td = @call.call_date.strftime("%d.%m.%Y")
          tr
            td Дата создание записи
            td = @call.created_at.strftime("%d.%m.%Y %H:%M")
          tr
            td Мастер
            td = @call.master&.name
          tr
            td Гарантийный
            td = t(@call.guarantee)
          - if @call.guarantee?
            tr
              td Серия
              td = @call.warranty ? (link_to @call.warranty.serial, warranty_path(@call.warranty)) : 'Гарантийный котел был удален'
          tr
            td Регистратор вызова
            td = @call.user.username
          tr
            td Комментарий
            td = @call.comment
          tr
            td Статус
            td
              span class="label label-#{@call.status}" = t(@call.status)
          - if comment_status(@call)
            tr
              td Комментарий к статусу
              td = comment_status(@call)
          tr
            td Сменить статус
            td.buttons
              = link_to 'Ожидает', call_expect_admin_call_path(@call), class: "btn btn-danger", method: :put if @call.status != 'expect'
              = link_to 'В процессе', call_in_progress_admin_call_path(@call), class: 'btn btn-warning', method: :put if @call.status != 'in_progress'
              = link_to 'Выполнен', '#modal_success', data: { toggle: :modal }, class: 'btn btn-success' if @call.status != 'success'
              = link_to 'Отменен', '#modal_canceled', data: { toggle: :modal }, class: 'btn bg-color-blueLight txt-color-white' if @call.status != 'canceled'

#modal_success.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal" aria-hidden="true" ×
        h4.modal-title Подтвердите выполнение вызова
      = form_for [:admin, @call] do |f|
        .modal-body
          .row
            .col-md-12
              = f.label :infosuccess, "Вам есть что сказать о выполнение вызова ?"
              = f.text_area :infosuccess, class: 'form-control', rows: 5
              = f.hidden_field :status, value: 'success'
        .modal-footer
          button.btn.btn-default type="button" data-dismiss="modal" Отменить
          = f.submit 'Сохранить', class: "btn btn-primary"

#modal_canceled.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal" aria-hidden="true" ×
        h4.modal-title Подтвердите отмену вызова
      = form_for [:admin, @call] do |f|
        .modal-body
          .row
            .col-md-12
            = f.label :whycanceled, "Не хотите рассказать почему пришлось отменить вызов?"
            = f.text_area :whycanceled, class: "form-control", rows: 5
            = f.hidden_field :status, value: 'canceled'
        .modal-footer
          button.btn.btn-default type="button" data-dismiss="modal" Отменить
          = f.submit 'Сохранить', class: "btn btn-danger"