config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: :login }, skip: [:registrations]
  as :user do
    get 'me/edit' => 'registrations#edit', :as => 'edit_user_registration'
    put 'user' => 'registrations#update', :as => 'user_registration'
  end

  root 'home#index'
  resources :calls, only: [:show, :index]
  resources :warranties, only: [:show, :index]

  namespace :admin do
    resources :users, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :warranties, except: [:show, :index] do
      get :fields_autocomplete, on: :collection
    end
    resources :calls, except: [:show, :index] do
      member do
        put :call_expect
        put :call_in_progress
      end
    end
    resources :boilers, except: [:show, :index] do
      resources :product_models, only: [:create, :update, :destroy], shallow: true
    end
    resources :masters, except: [:show, :index, :edit]
    resources :users, only: [:index, :show, :update, :destroy]

    get '/serial_autocomplete', to: 'calls#serial_autocomplete'
  end
end

app/models/scopes/warranty.rb
module Scopes
  module Warranty
    extend ActiveSupport::Concern

    included do
      scope :by_id, lambda { |id|
        where(id: id)
      }

      scope :by_datebuyed, lambda { |datebuyed|
        where('datebuyed > ?', datebuyed)
      }

      scope :by_name, lambda { |name|
        where('name ILIKE ?', "%#{name}%")
      }

      scope :by_product_model, lambda { |product_model_name|
        references(:product_model).where('product_models.name ILIKE ?', "%#{product_model_name}%")
      }

      scope :by_adress, lambda { |adress|
        where('adress ILIKE ?', "%#{adress}%")
      }

      scope :by_started, lambda { |started|
        where(started: started)
      }

      scope :by_master_name, lambda { |master_name|
        references(:master).where('masters.name ILIKE ?', "%#{master_name}%")
      }

      scope :by_datefirststart, lambda { |datefirststart|
        where('created_at > ?', datefirststart)
      }

      scope :by_created_at, lambda { |created_at|
        where('created_at > ?', created_at)
      }

      scope :serials, lambda { |term|
        where('serial ILIKE ?', "%#{term}%").limit(6).pluck(:serial)
      }

      scope :by_warranty_until, lambda { |warranty|
        case warranty
        when 'empty'
          where(warranty_until: nil)
        when 'enabled'
          where('warranty_until > ?', Time.current)
        when 'disabled'
          where('warranty_until < ?', Time.current)
        end
      }
    end
  end
end

app/models/warranty.rb
class Warranty < ApplicationRecord
  include PgSearch
  include Filterable
  include Scopes::Warranty

  validates :name, :adress, :phone, :datebuyed, :serial, presence: true
  validates :started, inclusion: { in: [true, false] }
  validates :master_id, :datefirststart, presence: true, if: -> { started? }
  validates :serial, uniqueness: { case_sensitive: false }

  before_save :clear_master_and_start

  has_many :calls
  belongs_to :product_model
  belongs_to :master, optional: true
  belongs_to :user

  pg_search_scope :search_by, against: %i[id name phone adress comment serial], using: { tsearch: { prefix: true } },
                              associated_against: { product_model: :name, master: :name }

  def self.pg_search(query)
    query.blank? ? [] : search_by(query)
  end

  def warranty_have?
    return 'empty' unless warranty_until
    warranty_until > Time.current
  end

  private

  def clear_master_and_start
    return if started?
    self.master = nil
    self.datefirststart = nil
  end
end

app/controllers/admin/warranties_controller.rb
class Admin::WarrantiesController < Admin::AdminController
  before_action :find_id, only: [:update, :edit, :destroy]
  def new
    @warranty = current_user.warranties.build
  end

  def create
    @warranty = current_user.warranties.build(warranty_params)
    if @warranty.save
      redirect_to warranties_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @warranty.update(warranty_params)
      redirect_to warranties_path
    else
      render :edit
    end
  end

  def destroy
    @warranty.destroy
    redirect_to warranties_path
  end

  def fields_autocomplete
    @warranty = Warranty.find_by('serial ILIKE ?', params[:serial])
    render json: @warranty
  end

  private

  def find_id
    @warranty = Warranty.find(params[:id])
  end

  def warranty_params
    params.require(:warranty).permit(:product_model_id, :name, :phone, :adress, :serial, :datefirststart, :master_id,
                                     :datebuyed, :started, :comment, :warranty_until)
  end
end

app/controllers/warranties_controller.rb
class WarrantiesController < ApplicationController
  include ApplicationHelper
  helper_method :sort_column, :sort_direction

  def index
    respond_to do |format|
      format.html
      format.json do
        scope = Warranty.all
        render json: ApplicationDatatable.new(view_context, scope.includes(:product_model, :master))
      end
    end
  end

  def show
    @warranty = Warranty.find(params[:id])
    @calls = @warranty.calls.paginate(page: params[:page], per_page: 15)
  end
end

app/helpers/warranties_helper.rb
module WarrantiesHelper
end

app/views/warranties/index.html.slim
section
  .row.mt5
    article.col-xs-12
      .jarviswidget.jarviswidget-color-blueDark
        header
          h2 Гарантийные
        div
          .widget-body.no-padding
            table#warranties.table.table-bordered.table-striped.mb0 cellspacing="0" width='100%' data-source="#{warranties_path(format: :json)}"
              thead
                tr
                  - WarrantyPresenter.columns.each do |column|
                    = k(:datatable_column, column).filter_cell
                tr
                  - WarrantyPresenter.columns.each do |column|
                    = k(:datatable_column, column).cell

app/views/warranties/show.html.slim
.row
  article.col-xs-12.col-sm-6.col-md-6.col-lg-6
    .jarviswidget.jarviswidget-color-blueDark.jarviswidget-sortable
      header.ui-sortable-handle
        span.widget-icon
          i.fa.fa-ambulance
        h2
          | Гарантийный котел #
          = @warranty.id
        .jarviswidget-ctrls
          = link_to edit_admin_warranty_path(@warranty), class: 'button-icon' do
            i.fa.fa-cog
          = link_to admin_warranty_path(@warranty), class: 'button-icon', method: :delete, data: { confirm: "Вы уверены что хотите удалить гарантию #{@warranty.name}?"} do
            i.fa.fa-trash
      div
        .widget-body
          table#warranty.table-hover.table.table-bordered.table-striped[style="clear: both"]
            tbody
              tr
                td style="width:25%;" Клиент
                td = @warranty.name
              tr
                td Котел
                td = @warranty.product_model.full_name
              tr
                td Телефон
                td = @warranty.phone
              tr
                td Адрес
                td
                  span.ymaps-geolink = @warranty.adress
              tr
                td Дата покупки
                td = @warranty.datebuyed.strftime("%d.%m.%Y")
              tr
                td Серийный номер
                td = @warranty.serial
              tr
                td Первый пуск
                td = t(@warranty.started)
              - if @warranty.started?
                tr
                  td Дата первого пуска
                  td = @warranty.datefirststart.strftime("%d.%m.%Y")
                tr
                  td Кто запускал
                  td = @warranty.master&.name
              tr
                td Дата создание записи
                td = @warranty.created_at.strftime("%d.%m.%Y %H:%M")
              tr
                td Регистратор гарантии
                td = @warranty.user.username
                tr
                  td Гарантия
                  td
                    span class="label label-#{@warranty.warranty_have?}" = t("warranty.#{@warranty.warranty_have?}")
              - if @warranty.warranty_until
                tr
                  td Гарантия действует до
                  td = @warranty.warranty_until&.strftime("%d.%m.%Y")
              tr
                td Комментарий
                td = @warranty.comment
  article.col-xs-12.col-sm-6.col-md-6.col-lg-6
    .jarviswidget.jarviswidget-color-blueDark.jarviswidget-sortable
      header.ui-sortable-handle
        span.widget-icon
          i.fa.fa-phone
        h2 Вызовы котла
      div
        .widget-body
          - if @calls.any?
            table#calls.table.table-hover.table-bordered.table-striped[style="clear: both"]
              thead
                tr
                  th ID
                  th Дата создания
                  th Статус
              tbody
                - @calls.each do |call|
                  tr
                    td = link_to "##{call.id}", call_path(call)
                    td = call.created_at.strftime("%d.%m.%Y")
                    td
                      span class="label label-#{call.status}" = t(call.status)
            .container
              = will_paginate @calls, renderer: 'BootstrapPaginationHelper::LinkRenderer'
          - else
            h3.text-center Список вызовов пуст