config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: :login }, skip: [:registrations]
  as :user do
    get 'me/edit' => 'registrations#edit', :as => 'edit_user_registration'
    put 'user' => 'registrations#update', :as => 'user_registration'
  end

  root 'home#index'
  resources :calls, only: [:show, :index]
  resources :warranties, only: [:show, :index]

  namespace :admin do
    resources :users, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :warranties, except: [:show, :index] do
      get :fields_autocomplete, on: :collection
    end
    resources :calls, except: [:show, :index] do
      member do
        put :call_expect
        put :call_in_progress
      end
    end
    resources :boilers, except: [:show, :index] do
      resources :product_models, only: [:create, :update, :destroy], shallow: true
    end
    resources :masters, except: [:show, :index, :edit]
    resources :users, only: [:index, :show, :update, :destroy]

    get '/serial_autocomplete', to: 'calls#serial_autocomplete'
  end
end

app/models/boiler.rb
class Boiler < ApplicationRecord
  has_many :product_models, dependent: :destroy

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/admin/boilers_controller.rb
class Admin::BoilersController < Admin::AdminController
  before_action :find_id, only: [:destroy, :edit, :update]
  before_action :boilers_all, only: [:new, :create]

  def new
    @boiler = Boiler.new
  end

  def create
    @boiler = Boiler.new(boiler_params)

    if @boiler.save
      redirect_to new_admin_boiler_path
    else
      render action: 'new'
    end
  end

  def update
    if @boiler.update(boiler_params)
      redirect_to new_admin_boiler_path
    else
      render :edit
    end
  end

  def destroy
    @boiler.destroy
  end

  private

  def find_id
    @boiler = Boiler.find(params[:id])
  end

  def boilers_all
    @boilers = Boiler.order(created_at: :desc).paginate(per_page: 10, page: params[:page])
  end

  def boiler_params
    params.require(:boiler).permit(:name)
  end
end

app/helpers/boilers_helper.rb
module BoilersHelper
end

app/views/admin/boilers/_form.html.slim
= render 'shared/errors', resource: resource
= form_for [:admin, resource], html: { class: 'smart-form' } do |f|
      section
        = f.label :name, "Марка", class: 'label'
        label.input
          = f.text_field :name, autofocus: true
      footer
        .left
          = f.submit resource.persisted? ? 'Сохранить' : 'Добавить марку', class: 'btn btn-primary'

app/views/admin/boilers/destroy.js.erb
$('.boiler<%= @boiler.id %>').remove();

app/views/admin/boilers/edit.html.slim
.col-sm-12
  .well
    h1 Редактировать марку
    = render 'form', resource: @boiler

app/views/admin/boilers/new.html.slim
.col-sm-12
  .well
    h1 Добавить марку
    = render 'form', resource: @boiler
  .row
    article.col-xs-12.col-sm-12.col-md-12.col-lg-12
      .jarviswidget.jarviswidget-color-blueDark.jarviswidget-sortable
        header.ui-sortable-handle
          span.widget-icon
            i.fa.fa-fire
          h2 Существующие марки
        div
          .widget-body
            - if @boilers.any?
              #accordion.panel-group.smart-accordion-default
                - @boilers.each do |boiler|
                  .panel.panel-default class="boiler#{boiler.id}"
                    .panel-heading
                      h4.panel-title
                        a.collapsed aria-expanded="false" data-parent="#accordion" data-toggle="collapse" href="#collapse#{boiler.id}"
                          i.fa.fa-fw.fa-plus-circle.txt-color-green
                          i.fa.fa-fw.fa-minus-circle.txt-color-red
                          = boiler.name
                          | (
                          span id="boiler_count_#{boiler.id}"
                            = boiler.product_models.count
                          | )
                    .panel-collapse.collapse id="collapse#{boiler.id}"
                      .panel-body.no-padding
                        table.table.table-bordered.table-condensed
                          thead
                            tr
                              th.text-center colspan="2"
                                = link_to 'Редактировать марку', edit_admin_boiler_path(boiler), class: 'btn btn-xs btn-warning mr5'
                                = link_to 'Удалить марку', admin_boiler_path(boiler), class: 'btn btn-xs btn-danger', method: :delete, data: { confirm: "Вы уверены что хотите удалить котел #{boiler.name}?"}, remote: true
                            tr
                              th Название
                              th Действия
                          tbody id="table_body_boiler_#{boiler.id}"
                            = render boiler.product_models
                          tr
                            td
                              = form_for [:admin, boiler, boiler.product_models.build], html: { class: 'smart-form' }, remote: true do |f|
                                span Добавить модель
                                = f.text_field :name, id: "product_model_name_#{boiler.id}"
                                = f.button class: 'btn btn-xs btn-primary ml5' do
                                  i.fa.fa-plus

              .container
                = will_paginate @boilers, renderer: 'BootstrapPaginationHelper::LinkRenderer'
            - else
              h3.text-center Список марок пуст