config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: :login }, skip: [:registrations]
  as :user do
    get 'me/edit' => 'registrations#edit', :as => 'edit_user_registration'
    put 'user' => 'registrations#update', :as => 'user_registration'
  end

  root 'home#index'
  resources :calls, only: [:show, :index]
  resources :warranties, only: [:show, :index]

  namespace :admin do
    resources :users, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :warranties, except: [:show, :index] do
      get :fields_autocomplete, on: :collection
    end
    resources :calls, except: [:show, :index] do
      member do
        put :call_expect
        put :call_in_progress
      end
    end
    resources :boilers, except: [:show, :index] do
      resources :product_models, only: [:create, :update, :destroy], shallow: true
    end
    resources :masters, except: [:show, :index, :edit]
    resources :users, only: [:index, :show, :update, :destroy]

    get '/serial_autocomplete', to: 'calls#serial_autocomplete'
  end
end

app/models/user.rb
class User < ApplicationRecord
  DESIGNS = { 0 => 'Smart Default', 1 => 'Dark Elegance', 2 => 'Ultra Light', 3 => 'Google Skin',
              4 => 'Pixel Smash', 5 => 'Glass', 6 => 'MaterialDesign' }.freeze

  devise :database_authenticatable, :recoverable,
         :rememberable, :trackable, :validatable, :registerable
  validates :username, presence: true
  validates :design, presence: true, inclusion: 0..6
  validate :validate_last_administrator, on: :update

  has_many :warranties
  has_many :calls

  def admin?
    is_a?(Admin)
  end

  private

  def validate_last_administrator
    if User.where(type: 'Admin').count <= 1 && type != 'Admin' && admin?
      errors.add(:base, 'Вы являетесь последним администратором.')
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  before_action :find_user, only: [:destroy, :edit, :update]

  def index
    @users = User.order(created_at: :DESC)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: 'Администратор успешно добавлен'
    else
      render :new
    end
  end

  def destroy
    if User.where(type: 'Admin').count == 1 && @user.admin?
      redirect_to admin_users_path, alert: 'Последний администратор не может быть удален.'
    else
      @user.destroy
      redirect_to admin_users_path, notice: 'Пользователь успешно удален.'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: 'Успешно обновлен'
    else
      render :edit
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation, :type)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.slim
.row
  article.col-xs-12.col-sm-6.col-md-6.col-lg-6
    .jarviswidget.jarviswidget-color-blueDark.jarviswidget-sortable
      header.ui-sortable-handle
        span.widget-icon
          i.fa.fa-user
        h2 Редактирование данных #{@user.username}
      div
        .widget-body
          = form_with model: [:admin, @user.becomes(User)], class: 'smart-form', local: true do |f|
            = render 'shared/errors', resource: @user
            fieldset
              .row
                section.col.col-6
                  label.input
                    i.icon-prepend.fa.fa-envelope-o
                    = f.email_field :email, autofocus: true, autocomplete: "email", placeholder: 'E-mail'
                section.col.col-6
                  label.input
                    i.icon-prepend.fa.fa-user
                    = f.text_field :username, autocomplete: "username", placeholder: 'Пользователь'
              .row
                section.col.col-6
                  label.select
                    = f.select :type, [['Администратор', 'Admin'],['Обычный пользователь','User']]
                    i
            footer
              .left
                = f.submit 'Сохранить', class: 'btn btn-primary'

  article.col-xs-12.col-sm-6.col-md-6.col-lg-6
    .jarviswidget.jarviswidget-color-blueDark.jarviswidget-sortable
      header.ui-sortable-handle
        span.widget-icon
          i.fa.fa-user
        h2 Смена пароля #{@user.username}
      div
        .widget-body
          = form_with model: [:admin, @user.becomes(User)], class: 'smart-form', local: true do |f|
            .row
              section.col.col-6
                label.input
                  i.icon-prepend.fa.fa-key
                  = f.password_field :password, autocomplete: "off", placeholder: 'Пароль'
            .row
              section.col.col-6
                label.input
                  i.icon-prepend.fa.fa-key
                  = f.password_field :password_confirmation, autocomplete: "off", placeholder: 'Повторите пароль'
            footer
              .left
                = f.submit 'Сменить', class: 'btn btn-primary'

app/views/admin/users/index.html.slim
.row
  article.col-xs-12.col-sm-12.col-md-12.col-lg-12
    .jarviswidget.jarviswidget-color-blueDark.jarviswidget-sortable
      header.ui-sortable-handle
        span.widget-icon
          i.fa.fa-group
        h2 Пользователи
        .jarviswidget-ctrls
          = link_to new_admin_user_path, class: 'button-icon' do
            i.fa.fa-plus
      div
        .widget-body
          table#users.table-hover.table.table-bordered.table-striped
            thead
              tr
                th #
                th Email
                th Пользователь
                th Роль
                th
                th
            tbody
              - @users.each do |user|
                tr
                  td = user.id
                  td = user.email
                  td = user.username
                  td = t(user.type)
                  td = link_to 'Редактировать', edit_admin_user_path(user), class: 'btn btn-warning'
                  td = link_to "Удалить", admin_user_path(user), method: :delete, data: { confirm: 'Вы уверены?' }, class: 'btn btn-danger'

app/views/admin/users/new.html.slim
.row
  article.col-xs-12.col-sm-12.col-md-12.col-lg-12
    .jarviswidget.jarviswidget-color-blueDark.jarviswidget-sortable
      header.ui-sortable-handle
        span.widget-icon
          i.fa.fa-user
        h2 Новый пользователь
      div
        .widget-body
          = form_with model: [:admin, @user.becomes(User)], class: 'smart-form', local: true do |f|
            = render 'shared/errors', resource: @user
            fieldset
              .row
                section.col.col-6
                  label.input
                    i.icon-prepend.fa.fa-envelope-o
                    = f.email_field :email, autofocus: true, autocomplete: "email", placeholder: 'E-mail'
                section.col.col-6
                  label.input
                    i.icon-prepend.fa.fa-user
                    = f.text_field :username, autocomplete: "username", placeholder: 'Пользователь'
              .row
                section.col.col-6
                  label.input
                    i.icon-prepend.fa.fa-key
                    = f.password_field :password, autocomplete: "off", placeholder: 'Пароль'
                section.col.col-6
                  label.input
                    i.icon-prepend.fa.fa-key
                    = f.password_field :password_confirmation, autocomplete: "off", placeholder: 'Повторите пароль'
              .row
                section.col.col-6
                  label.select
                    = f.select :type, [['Администратор', 'Admin'],['Обычный пользователь','User']]
                    i
            footer
              .left
                = f.submit 'Зарегистрировать', class: 'btn btn-primary'